permalink   : pretty
markdown    : kramdown
highlighter : pygments

paginate: 4 #6
comments: true
paginate_path: "/page/:num"

gems: [jekyll-paginate]

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Kevin Farst's Blog
description: "Ramblings about code and stuff"
email: farst.6@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "http://github.com/kfarst"
repository: "http://github.com/kfarst"
disqus_shortname: "kfarst"
google_analytics: UA-89422990-1

# social footer
social:
  github:
    slug: github
    link: http://github.com/kfarst
  twitter:
    slug: twitter
    link: http://twitter.com/kevinfarst
  linkedin:
    slug: linkedin
    link: https://www.linkedin.com/in/kevin-farst-14a63914

category_archive:
  slugify: true
