permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site

# Site settings
title: Lora
description: "A free Jekyll theme"
email: your-email@domain.com
baseurl: "/lora" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "http://nandomoreira.me/lora"
repository: "https://github.com/nandomoreirame/lora"
google_analytics: UA-52446115-1
